### ISSUE TITLE
[ISSUE] To Remove Redundant Use of Footer in Each Route

### ISSUE THREAD

**Issue by Atharv-110** [Ashpara10/acm-website#40]
## Problem
In every router FooterSection component is being imported and used. When it should only be rendered once in whole web app.

## Fix Area
- Remove redundant/repeated imports
- Import it in `Layout.tsx`, So that it will be rendered only once in whole web app.

This issue is accepted in Hacktoberfest 2024.

**Comment by AnugrahAsh** [comment]
## Request to fix this issue 

@ramxcodes @Atharv-110
I can fix this problem, please assign this issue to me

**Comment by Atharv-110** [comment]
@AnugrahAsh Good! Go Ahead! Assigning it to you.
