### ISSUE TITLE
[ISSUE] Favicon Not Visible on All Routes

### ISSUE THREAD

**Issue by Atharv-110** [Ashpara10/acm-website#42]
## Problem Statement
Favicon is visible on only home page and not on other routes.

## Fix Logic
- Use Next.js Feature to load favicon in all the pages

This issue will be considered in Hacktoberfest 2024.

**Comment by larrikin-coder** [comment]
please assign me the issue @Atharv-110

**Comment by tanyasomwanshi** [comment]
Please assign this issue to me @Atharv-110

**Comment by Atharv-110** [comment]
@larrikin-coder You can raise another issue but this one is already informed to us by @tanyasomwanshi.

@tanyasomwanshi assigning to you, go ahead!

**Comment by larrikin-coder** [comment]
already fixed the issue and created a PR  review and merge please sorry :( please @Atharv-110 @tanyasomwanshi
