### ISSUE TITLE
[ENHANCEMENT] Reduce content on About page

### ISSUE THREAD

**Issue by Ashpara10** [Ashpara10/acm-website#67]
The current "About" section contains a lot of details that may not be necessary for users. We need to make it more concise, to the point, and focused on essential information only.

## Tasks
- Identify and remove any redundant or overly detailed information.
- Rewrite the "About" section to maintain clarity while reducing its length.
- Ensure the revised text aligns with our community and provides a clear summary of MUACM’s purpose.

**Comment by tanyasomwanshi** [comment]
Please assign this issue to me.
@Ashpara10 @Atharv-110
