### ISSUE TITLE
 [ENHANCEMENT] Fix Inconsistencies in Testimonials Section

### ISSUE THREAD

**Issue by Ashpara10** [Ashpara10/acm-website#68]
The width of the Testimonials section currently does not match the width of other sections on the site, creating a lack of visual cohesion. This issue should be addressed to improve the site's overall design consistency.

## Tasks
- Adjust the Testimonials section width to match the width of other sections.
- Ensure that the changes are responsive and display correctly on all devices.
- Test for alignment and verify that the section looks visually consistent across the site.

**Comment by tanyasomwanshi** [comment]
@Ashpara10 @Atharv-110 
Please assign this issue to me.
