### ISSUE TITLE
[ENHANCEMENT] Update Carousel Images to Event-Specific Images

### ISSUE THREAD

**Issue by Ashpara10** [Ashpara10/acm-website#69]
The images in the carousel on the dynamic events page currently do not correspond to each event and lack a consistent aspect ratio. To improve consistency and relevance, each event should display images specific to it, formatted in a video aspect ratio.

## Tasks
- Source and replace carousel images with event-specific visuals.
- Ensure each image is cropped/resized to a standard video aspect ratio (16:9).
- Test across devices to verify consistent display and alignment.

**Comment by tanyasomwanshi** [comment]
@Ashpara10 @Atharv-110 
Please assign this issue to me.
