### ISSUE TITLE
Adding glassmorphism to navbar and fixing excess delay on animations

### ISSUE THREAD

**Issue by Ashpara10** [Ashpara10/acm-website#80]
## Changes to be made
- adding glassmorphism to navbar for sleek and modern design
- reducing delay on fade in animations

@Atharv-110 @ramxcodes @AnugrahAsh 
 Please assign this issue to me and add Hacktoberfest label to it.

Thanks & Regards,
Ashwin Parande

**Comment by akshat3144** [comment]
Done, created a new branch "nav-fade-in" and sent a pull request

**Comment by AnugrahAsh** [comment]
@Ashpara10 Assigned it to you,
Go ahead as you requested for it first
